Make script work on ubuntu github CI

diff --git a/scripts/ubuntu-install-test-no-nix b/scripts/ubuntu-install-test-no-nix
--- a/scripts/ubuntu-install-test-no-nix
+++ b/scripts/ubuntu-install-test-no-nix
@@ -3,15 +3,20 @@
 # using Nix on ubuntu. It's not recommended to run it outside of a container or
 # otherwise ephemeral environment like the CI.
 set -e
-# Execute all lines that start with four spaces, and remove leading 'sudo '
-# because we're in a container and already root.
 #
-# Also skip cloning the repo and changing directories, because we want to test
-# with the current code and not what's in the main branch.
-grep '^    ' doc/ubuntu.md \
-    | sed 's/^    //' \
-    | sed 's/^sudo //' \
-    | sed 's/| sudo /| /' \
-    | sed 's/^cd .*//' \
-    | sed 's/^git clone .*//' \
-    | bash -exo pipefail
+# Execute the ubuntu installation instructions from doc/ubuntu.md
+#
+# Skip cloning the repo and changing directories, because we want to test with
+# the current code and not what's in the main branch.
+SCRIPT="$(grep '^    ' doc/ubuntu.md | sed 's/^    //' | sed 's/^cd .*//' | sed 's/^git clone .*//')"
+
+# Remove sudo if we're already root
+if [ "$(whoami)" == root ]; then
+    SCRIPT="$(echo "$SCRIPT" | sed 's/^sudo //' | sed 's/| sudo /| /')"
+fi
+
+echo "Will execute:"
+echo "$SCRIPT"
+echo
+
+echo "$SCRIPT" | bash -exo pipefail
